# Generated by Django 6.0.5 on 2026-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('launchpad', 'Launchpad Project'), ('launchpad_package', 'Launchpad Package'), ('github', 'GitHub Issues'), ('bugzilla', 'Bugzilla')], max_length=50)),
                ('identifier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('last_updated', models.DateTimeField()),
                ('sources', models.ManyToManyField(related_name='bugs', to='dashboard.bugsource')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='GitHubPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('repo', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('state', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bugs', models.ManyToManyField(related_name='github_prs', to='dashboard.bug')),
            ],
            options={
                'ordering': ['-pr_number'],
                'unique_together': {('repo', 'pr_number')},
            },
        ),
    ]
