# Generated by Django 6.0.5 on 2026-05-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_seed_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('match_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bugs', models.ManyToManyField(related_name='correlations', to='dashboard.bug')),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
    ]
