# Generated by Django 6.0.5 on 2026-05-13 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bugcorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcorrelation',
            name='confidence_score',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
