# Generated by Django 6.0.5 on 2026-05-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_bugcorrelation_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dashboard.preset')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('preset', 'name')},
            },
        ),
    ]
