# Generated by Django 6.0.5 on 2026-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_bugcorrelation_confidence_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='You are a bug triage assistant. Analyze the bug report and provide a concise summary covering: root cause, affected components, reproduction steps, impact severity, and any workarounds mentioned.')),
                ('auto_analyze_max_bytes', models.IntegerField(default=51200)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Configuration',
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='analysis_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
