# Generated by Django 6.0.5 on 2026-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bug_tags_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bug',
            name='tags',
        ),
        migrations.AddField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bugs', to='dashboard.tag'),
        ),
    ]
