# Generated by Django 6.0.5 on 2026-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_analysisconfig_bug_analysis_bug_analysis_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
