# Generated by Django 6.0.5 on 2026-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_analysisconfig_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
